# Generated by Django 3.2.16 on 2024-02-18 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customizer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='主题名称', max_length=100)),
                ('code', models.IntegerField(default=0, help_text='主题编码', null=True)),
                ('zh_name', models.CharField(help_text='主题中文名称', max_length=100)),
                ('value', models.IntegerField(default=0, help_text='主题值', null=True)),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('remark', models.TextField(default=None, help_text='备注', null=True)),
                ('user', models.ForeignKey(default='', help_text='用户ID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customizer',
            },
        ),
    ]
