# Generated by Django 3.2.16 on 2024-02-20 22:48

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0002_author_poetry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='公司编码', max_length=50)),
                ('pinyin_code', models.CharField(help_text='拼音编码', max_length=50)),
                ('name', models.CharField(help_text='公司名称', max_length=100)),
                ('address', models.CharField(help_text='公司地址', max_length=200)),
                ('telephone', models.CharField(help_text='联系方式', max_length=100)),
                ('status', models.IntegerField(default=0, help_text='公司状态', null=True)),
                ('type', models.IntegerField(default=0, help_text='公司类型', null=True)),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存时间')),
                ('remark', models.TextField(default=None, help_text='备注', null=True)),
            ],
            options={
                'db_table': 'partners',
            },
        ),
    ]
