# Generated by Django 3.2.16 on 2024-02-21 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nb', '0003_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='user',
            field=models.ForeignKey(default='', help_text='用户ID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partners',
            name='address',
            field=models.CharField(help_text='伙伴地址', max_length=200),
        ),
        migrations.AlterField(
            model_name='partners',
            name='code',
            field=models.CharField(help_text='伙伴编码', max_length=50),
        ),
        migrations.AlterField(
            model_name='partners',
            name='name',
            field=models.CharField(help_text='伙伴名称', max_length=100),
        ),
        migrations.AlterField(
            model_name='partners',
            name='status',
            field=models.IntegerField(default=0, help_text='伙伴状态', null=True),
        ),
        migrations.AlterField(
            model_name='partners',
            name='type',
            field=models.IntegerField(default=0, help_text='伙伴类型', null=True),
        ),
    ]
