# Generated by Django 3.2.16 on 2024-02-24 19:49

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0005_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='消息内容', max_length=20)),
                ('obj_id', models.CharField(help_text='对象ID', max_length=50, null=True)),
                ('type', models.CharField(help_text='跳转页面', max_length=20, null=True)),
                ('date', models.DateTimeField(help_text='写入时间', null=True, verbose_name='写入时间')),
                ('is_look', models.BooleanField(default=False, help_text='是否已读')),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存时间')),
            ],
            options={
                'db_table': 'message',
            },
        ),
    ]
